FROM node:latest as storybook
COPY . ./
RUN npm ci
RUN npm run build-scss
RUN npm run build-storybook
RUN npm run release

# copy /release/x.y.z/ to cdn

FROM nginx:alpine
COPY --from=storybook ./storybook-static /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]