FROM node:20 as storybook
WORKDIR /usr/veera
COPY ./package.json ./
RUN npm i
COPY ./ ./
RUN npm run build-scss
RUN npm run build-storybook
RUN npm run release

# copy /release/x.y.z/ to cdn

FROM nginx:alpine
COPY --from=storybook /usr/veera/storybook-static /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]